# Generated by Django 5.2.1 on 2025-06-04 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0002_amcagreement_bmcagreement_cattlefeedagreement_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='first_name',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='last_name',
            field=models.CharField(max_length=250, null=True),
        ),
    ]
