# Generated by Django 5.2.1 on 2025-06-04 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0003_customuser_first_name_customuser_last_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='profile_picture',
            field=models.ImageField(blank=True, help_text='Upload a profile picture (JPG, PNG, Max 2MB)', null=True, upload_to='profile_pics/'),
        ),
    ]
