# Generated by Django 5.2.1 on 2025-06-05 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0004_customuser_profile_picture'),
    ]

    operations = [
        migrations.AddField(
            model_name='amcagreement',
            name='document_pending',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='amcagreement',
            name='document_status',
            field=models.CharField(choices=[('INCOMPLETE', 'INCOMPLETE'), ('COMPLETE', 'COMPLETE')], default='INCOMPLETE', max_length=20),
        ),
        migrations.AddField(
            model_name='bmcagreement',
            name='document_pending',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='bmcagreement',
            name='document_status',
            field=models.CharField(choices=[('INCOMPLETE', 'INCOMPLETE'), ('COMPLETE', 'COMPLETE')], default='INCOMPLETE', max_length=20),
        ),
        migrations.AddField(
            model_name='cattlefeedagreement',
            name='document_pending',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='cattlefeedagreement',
            name='document_status',
            field=models.CharField(choices=[('INCOMPLETE', 'INCOMPLETE'), ('COMPLETE', 'COMPLETE')], default='INCOMPLETE', max_length=20),
        ),
        migrations.AddField(
            model_name='consultantagreement',
            name='document_pending',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='consultantagreement',
            name='document_status',
            field=models.CharField(choices=[('INCOMPLETE', 'INCOMPLETE'), ('COMPLETE', 'COMPLETE')], default='INCOMPLETE', max_length=20),
        ),
        migrations.AddField(
            model_name='cookagreement',
            name='document_pending',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='cookagreement',
            name='document_status',
            field=models.CharField(choices=[('INCOMPLETE', 'INCOMPLETE'), ('COMPLETE', 'COMPLETE')], default='INCOMPLETE', max_length=20),
        ),
        migrations.AddField(
            model_name='distributeragreement',
            name='document_pending',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='distributeragreement',
            name='document_status',
            field=models.CharField(choices=[('INCOMPLETE', 'INCOMPLETE'), ('COMPLETE', 'COMPLETE')], default='INCOMPLETE', max_length=20),
        ),
        migrations.AddField(
            model_name='godownagreement',
            name='document_pending',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='godownagreement',
            name='document_status',
            field=models.CharField(choices=[('INCOMPLETE', 'INCOMPLETE'), ('COMPLETE', 'COMPLETE')], default='INCOMPLETE', max_length=20),
        ),
        migrations.AddField(
            model_name='guesthouseagreement',
            name='document_pending',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='guesthouseagreement',
            name='document_status',
            field=models.CharField(choices=[('INCOMPLETE', 'INCOMPLETE'), ('COMPLETE', 'COMPLETE')], default='INCOMPLETE', max_length=20),
        ),
        migrations.AddField(
            model_name='mccagreement',
            name='document_pending',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='mccagreement',
            name='document_status',
            field=models.CharField(choices=[('INCOMPLETE', 'INCOMPLETE'), ('COMPLETE', 'COMPLETE')], default='INCOMPLETE', max_length=20),
        ),
        migrations.AddField(
            model_name='milksaleagreement',
            name='document_pending',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='milksaleagreement',
            name='document_status',
            field=models.CharField(choices=[('INCOMPLETE', 'INCOMPLETE'), ('COMPLETE', 'COMPLETE')], default='INCOMPLETE', max_length=20),
        ),
        migrations.AddField(
            model_name='mpacsagreement',
            name='document_pending',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='mpacsagreement',
            name='document_status',
            field=models.CharField(choices=[('INCOMPLETE', 'INCOMPLETE'), ('COMPLETE', 'COMPLETE')], default='INCOMPLETE', max_length=20),
        ),
        migrations.AddField(
            model_name='officeleaseagreement',
            name='document_pending',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='officeleaseagreement',
            name='document_status',
            field=models.CharField(choices=[('INCOMPLETE', 'INCOMPLETE'), ('COMPLETE', 'COMPLETE')], default='INCOMPLETE', max_length=20),
        ),
        migrations.AddField(
            model_name='rentalbmcagreement',
            name='document_pending',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='rentalbmcagreement',
            name='document_status',
            field=models.CharField(choices=[('INCOMPLETE', 'INCOMPLETE'), ('COMPLETE', 'COMPLETE')], default='INCOMPLETE', max_length=20),
        ),
        migrations.AddField(
            model_name='rtaagreement',
            name='document_pending',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='rtaagreement',
            name='document_status',
            field=models.CharField(choices=[('INCOMPLETE', 'INCOMPLETE'), ('COMPLETE', 'COMPLETE')], default='INCOMPLETE', max_length=20),
        ),
    ]
