# Generated by Django 5.2.1 on 2025-06-14 06:06

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0007_amcagreement_created_by_amcagreement_updated_by_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='amcagreement',
            options={},
        ),
        migrations.RenameField(
            model_name='amcagreement',
            old_name='location',
            new_name='product',
        ),
        migrations.RemoveField(
            model_name='amcagreement',
            name='zone',
        ),
        migrations.AlterField(
            model_name='amcagreement',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_amcagreements', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='amcagreement',
            name='document',
            field=models.FileField(help_text='PDF, JPG, or PNG (Max 5MB)', upload_to='amc_agreements/', validators=[django.core.validators.FileExtensionValidator(['pdf', 'jpg', 'jpeg', 'png'])]),
        ),
        migrations.AlterField(
            model_name='amcagreement',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_amcagreements', to=settings.AUTH_USER_MODEL),
        ),
    ]
