# Generated by Django 5.2.1 on 2025-06-17 04:29

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0008_alter_amcagreement_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='InputServicesAgreement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product', models.CharField(max_length=100)),
                ('contractor', models.CharField(max_length=100)),
                ('pan', models.CharField(max_length=20)),
                ('type_of_agreement', models.CharField(max_length=100)),
                ('agreement_date', models.DateField()),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('tenure_months', models.IntegerField()),
                ('lock_in_period', models.CharField(max_length=100)),
                ('monthly_payout', models.DecimalField(decimal_places=2, max_digits=12)),
                ('document_status', models.CharField(choices=[('INCOMPLETE', 'INCOMPLETE'), ('COMPLETE', 'COMPLETE'), ('EXPIRE', 'EXPIRE')], default='INCOMPLETE', max_length=20)),
                ('document_pending', models.CharField(blank=True, max_length=255, null=True)),
                ('document', models.FileField(help_text='PDF, JPG, or PNG (Max 5MB)', upload_to='input_services_agreements/', validators=[django.core.validators.FileExtensionValidator(['pdf', 'jpg', 'jpeg', 'png'])])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_inputservicesagreements', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_inputservicesagreements', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Input Services Agreement',
                'verbose_name_plural': 'Input Services Agreements',
            },
        ),
        migrations.DeleteModel(
            name='CattleFeedAgreement',
        ),
    ]
