# Generated by Django 5.2.1 on 2025-06-17 05:48

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0009_inputservicesagreement_delete_cattlefeedagreement'),
    ]

    operations = [
        migrations.AlterField(
            model_name='amcagreement',
            name='document',
            field=models.FileField(help_text='PDF, JPG, or PNG (Max 5MB)', max_length=500, upload_to='amc_agreements/', validators=[django.core.validators.FileExtensionValidator(['pdf', 'jpg', 'jpeg', 'png'])]),
        ),
        migrations.AlterField(
            model_name='inputservicesagreement',
            name='document',
            field=models.FileField(help_text='PDF, JPG, or PNG (Max 5MB)', max_length=500, upload_to='input_services_agreements/', validators=[django.core.validators.FileExtensionValidator(['pdf', 'jpg', 'jpeg', 'png'])]),
        ),
    ]
