# Generated by Django 5.2.1 on 2025-06-18 09:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0010_alter_amcagreement_document_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='amcagreement',
            options={'verbose_name': 'AMC Agreement', 'verbose_name_plural': 'AMC Agreements'},
        ),
    ]
