# Generated by Django 5.2.1 on 2025-06-18 10:15

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0011_alter_amcagreement_options'),
    ]

    operations = [
        migrations.RenameField(
            model_name='consultantagreement',
            old_name='location',
            new_name='category',
        ),
        migrations.RemoveField(
            model_name='consultantagreement',
            name='zone',
        ),
        migrations.AlterField(
            model_name='consultantagreement',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_consultantagreements', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='consultantagreement',
            name='document',
            field=models.FileField(help_text='PDF, JPG, or PNG (Max 5MB)', max_length=500, upload_to='consultant_agreements/', validators=[django.core.validators.FileExtensionValidator(['pdf', 'jpg', 'jpeg', 'png'])]),
        ),
        migrations.AlterField(
            model_name='consultantagreement',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_consultantagreements', to=settings.AUTH_USER_MODEL),
        ),
    ]
