# Generated by Django 5.2.1 on 2025-06-20 05:11

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0012_rename_location_consultantagreement_category_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bmcagreement',
            name='document',
            field=models.FileField(help_text='PDF, JPG, or PNG (Max 5MB)', max_length=500, upload_to='agreements/', validators=[django.core.validators.FileExtensionValidator(['pdf', 'jpg', 'jpeg', 'png'])]),
        ),
        migrations.AlterField(
            model_name='cookagreement',
            name='document',
            field=models.FileField(help_text='PDF, JPG, or PNG (Max 5MB)', max_length=500, upload_to='agreements/', validators=[django.core.validators.FileExtensionValidator(['pdf', 'jpg', 'jpeg', 'png'])]),
        ),
        migrations.AlterField(
            model_name='distributeragreement',
            name='document',
            field=models.FileField(help_text='PDF, JPG, or PNG (Max 5MB)', max_length=500, upload_to='agreements/', validators=[django.core.validators.FileExtensionValidator(['pdf', 'jpg', 'jpeg', 'png'])]),
        ),
        migrations.AlterField(
            model_name='godownagreement',
            name='document',
            field=models.FileField(help_text='PDF, JPG, or PNG (Max 5MB)', max_length=500, upload_to='agreements/', validators=[django.core.validators.FileExtensionValidator(['pdf', 'jpg', 'jpeg', 'png'])]),
        ),
        migrations.AlterField(
            model_name='guesthouseagreement',
            name='document',
            field=models.FileField(help_text='PDF, JPG, or PNG (Max 5MB)', max_length=500, upload_to='agreements/', validators=[django.core.validators.FileExtensionValidator(['pdf', 'jpg', 'jpeg', 'png'])]),
        ),
        migrations.AlterField(
            model_name='mccagreement',
            name='document',
            field=models.FileField(help_text='PDF, JPG, or PNG (Max 5MB)', max_length=500, upload_to='agreements/', validators=[django.core.validators.FileExtensionValidator(['pdf', 'jpg', 'jpeg', 'png'])]),
        ),
        migrations.AlterField(
            model_name='milksaleagreement',
            name='document',
            field=models.FileField(help_text='PDF, JPG, or PNG (Max 5MB)', max_length=500, upload_to='agreements/', validators=[django.core.validators.FileExtensionValidator(['pdf', 'jpg', 'jpeg', 'png'])]),
        ),
        migrations.AlterField(
            model_name='mpacsagreement',
            name='document',
            field=models.FileField(help_text='PDF, JPG, or PNG (Max 5MB)', max_length=500, upload_to='agreements/', validators=[django.core.validators.FileExtensionValidator(['pdf', 'jpg', 'jpeg', 'png'])]),
        ),
        migrations.AlterField(
            model_name='officeleaseagreement',
            name='document',
            field=models.FileField(help_text='PDF, JPG, or PNG (Max 5MB)', max_length=500, upload_to='agreements/', validators=[django.core.validators.FileExtensionValidator(['pdf', 'jpg', 'jpeg', 'png'])]),
        ),
        migrations.AlterField(
            model_name='rentalbmcagreement',
            name='document',
            field=models.FileField(help_text='PDF, JPG, or PNG (Max 5MB)', max_length=500, upload_to='agreements/', validators=[django.core.validators.FileExtensionValidator(['pdf', 'jpg', 'jpeg', 'png'])]),
        ),
        migrations.AlterField(
            model_name='rtaagreement',
            name='document',
            field=models.FileField(help_text='PDF, JPG, or PNG (Max 5MB)', max_length=500, upload_to='agreements/', validators=[django.core.validators.FileExtensionValidator(['pdf', 'jpg', 'jpeg', 'png'])]),
        ),
    ]
